spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.web.resources.static-locations=file:uploads/,classpath:/static/,classpath:/public/
spring.web.resources.add-mappings=true
spring.web.resources.cache.period=0

app.base-url=http://localhost:8080
qr.image.directory=uploads/qr-codes/

aza.api.key=${AZA_API_KEY}
aza.api.url=https://api.aza.systems/api/v1/merchant